version: '3'
    services:
        app:
            container_name: alx_backend
            restart: always
            ports:
                - '6000:3000'
            links:
                - mongodb
        mongodb:
            container_name: mongo
            image: mongo:latest
            ports:
                - '27017:27017'