version: '3.5'
services:
    api.case:
        ports:
            - 3300:3000
        volumes:
            - .:/app
        command: sh -c "npx sequelize-cli db:migrate && npm run dev"

        environment:
            - DB_CONNECT = mongodb://127.0.0.1:27017/alx-db
            - TOKEN_SECRET = jwt_secret_token
    db:
        environment:
            - DB_CONNECT = mongodb://127.0.0.1:27017/alx-db
            - TOKEN_SECRET = jwt_secret_token
        volumes:
            - ~/case_data:/var/lib/postgresql/data
